#!/bin/bash -ex

cd ~

apt-get update
apt-get install eos-dev

wget http://c758482.r82.cf2.rackcdn.com/sublime-text_build-3083_i386.deb

dpkg -i sublime-text_build-3059_i386.deb

## ZSH ##
curl -L http://install.ohmyz.sh | sh
chsh -s `which zsh`
# Logout and log back in
source ~/.zshrc


### JHBUILD ###

git clone git://git.gnome.org/jhbuild

cd jhbuild
./autogen.sh
make
make install

### Now run ./link inside the dotfiles directory
source ~/.zshrc
###
# Create new SSH key and add it to github account
### GET DEPENDENCIES ###
apt-file update
jhbuild sysdeps --install
jhbuild build

